---
# https://docs.travis-ci.com/user/customizing-the-build

os: linux

dist: focal

git:
  depth: false

language: python
python:
  - "3.7"
  - "3.8"

# Install dependencies
install:
  # Install redis
  - apt-get update -y
  - apt-get install software-properties-common -y
  - add-apt-repository ppa:redislabs/redis -y
  - apt-get update -y
  - apt-get install redis -y
  # Install quantum-robot
  - pip install -e .
  # for CodeCov integration:
  - pip install coverage

# command to run tests
script:
  # start redis server
  - service redis-server start
  # run tests without coverage:
  # - pytest
  # run tests with coverage:
  - coverage run -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
