---
# https://docs.travis-ci.com/user/customizing-the-build

os: linux

dist: focal

git:
  depth: false

language: python
python:
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  # install redis
  - sudo add-apt-repository ppa:redislabs/redis  -y
  - sudo apt-get update -y
  - sudo apt-get install redis  -y
  # install the required packages:
  - pip install -r requirements.txt
  # install quantum-robot package:
  - pip install -e .
  # for CodeCov integration:
  - pip install coverage

# command to run tests
script:
  # start redis server
  # - service redis-server start
  # run tests without coverage:
  # - pytest
  # run tests with coverage:
  - coverage run -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
