# https://docs.travis-ci.com/user/customizing-the-build

os: linux

dist: 
- bionic
- xenial

git:
  depth: false

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e . # install quantum-robot package
  - pip install coverage # for CodeCov integration

# command to run tests
script:
  # - pytest # (without coverage)
  - coverage run -m pytest # (with coverage)

after_success:
  - bash <(curl -s https://codecov.io/bash)
