name: quantum-robot
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - "pytest>=5.4.3"
  - "dash>=2.0.0"
  - "matplotlib>=2.1.1"
  - "numpy>=1.18.5"
  - "pandas>=1.0.4"
  - "seaborn>=0.10.1"
  - pip:
    - "qiskit>=0.30.1"
    - redisconda info --envs
